add_newline = false

[line_break]
disabled = true

[character]
format = "$symbol "
success_symbol = "[\\$](green)"
error_symbol = "[\\$](red)"

[shell]
bash_indicator = ""
unknown_indicator = ""
powershell_indicator = " PS"
style = "gray"
disabled = false

[directory]
style = "italic"

[username]
style_user = "purple"
style_root = "bold red"
format = "[$user]($style) "

[hostname]
ssh_symbol = ""
format = "\b@[$ssh_symbol$hostname]($style) "

[git_branch]
format = "[<$symbol$branch]($style)"
style = "blue"
symbol = ""

[git_status]
format = "[$all_status$ahead_behind]($style)[>](blue)"
style = "cyan"

[hg_branch]
disabled = false
format = "[<$symbol$branch>]($style)"
style = "blue"
symbol = ""

[haskell]
format = " [$symbol([$version](italic $style))]($style)"
style = "red"

[package]
disabled = true

[aws]
disabled = true

[azure]
disabled = true

[battery]
disabled = true

[deno]
disabled = true

[dotnet]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true
